# Welcome to Jekyll!

# Site settings
title: Music Technology conference list
description: > # this means to ignore newlines until "baseurl:"
  A list of upcoming conferences and journal calls for the music technology community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://conferences.smcnetwork.org" # the base hostname & protocol for your site
twitter_username: mtg_upf
github_username:  mtg

# Build settings
markdown: kramdown
collections:
 - conferences
 - journals
